name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IDF_VERSION: v5.2.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: espressif/setup-esp-idf@v1
        with:
          version: ${{ env.IDF_VERSION }}
      - run: idf.py set-target esp32s3
      - run: idf.py build
      - uses: actions/upload-artifact@v4
        with:
          name: esp32s3-artifacts
          path: build/*
