name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: espressif/idf:release-v5.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure ESP-IDF environment is sourced so idf.py is in PATH
      - name: Set ESP32-S3 target
        run: . $IDF_PATH/export.sh && idf.py set-target esp32s3

      - name: Build firmware
        run: . $IDF_PATH/export.sh && idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tomo1firmware-${{ github.sha }}
          path: |
            build/*.bin
            build/*.elf
            build/*.map

