name: ESP32S3 Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git $HOME/esp-idf

      - name: Build firmware
        run: |
          source $HOME/esp-idf/export.sh
          idf.py build
