name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install ESP-IDF dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip cmake ninja-build ccache libffi-dev libssl-dev dfu-util

      # 3. Cache pip dependencies to speed up builds
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Get ESP-IDF
      - name: Clone ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git /home/runner/esp-idf
          cd /home/runner/esp-idf && git checkout v5.1.2  # lock to stable version

      # 5. Install Python requirements (FIXED PATH)
      - name: Install Python dependencies
        run: |
          pip install -r /home/runner/esp-idf/tools/requirements/requirements.core.txt

      # 6. Export ESP-IDF environment
      - name: Export ESP-IDF
        run: |
          . /home/runner/esp-idf/export.sh

      # 7. Build firmware
      - name: Build project
        run: |
          idf.py set-target esp32s3
          idf.py build
