name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # restrict GITHUB_TOKEN to read-only

    container:
      image: espressif/idf:release-v5.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache ESP-IDF dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.espressif
            ~/.cache
          key: ${{ runner.os }}-espidf-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-espidf-

      - name: Set up ESP-IDF target
        run: . $IDF_PATH/export.sh && idf.py set-target esp32s3

      - name: Build firmware
        run: . $IDF_PATH/export.sh && idf.py build

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tomo-pendant-firmware
          path: |
            build/*.bin
            build/*.elf
            build/*.map
