name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git ~/esp-idf
          cd ~/esp-idf
          git checkout v5.2.1
          ./install.sh esp32s3

      - name: Build firmware with idf.py
        run: |
          export IDF_PATH=$HOME/esp-idf
          . $IDF_PATH/export.sh
          cd $GITHUB_WORKSPACE
          idf.py set-target esp32s3
          idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-artifacts
          path: build/*
