name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Python and pip tools
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip tooling
        run: |
          python -m pip install --upgrade pip setuptools wheel

      # Step 3: Install ESP-IDF
      - name: Clone ESP-IDF
        run: |
          git clone --branch v5.2.1 --recursive https://github.com/espressif/esp-idf.git $HOME/esp-idf
          $HOME/esp-idf/install.sh esp32s3

      - name: Export ESP-IDF
        run: |
          echo "IDF_PATH=$HOME/esp-idf" >> $GITHUB_ENV
          source $HOME/esp-idf/export.sh
          python -m pip install -r $HOME/esp-idf/requirements.txt

      # Step 4: Build firmware
      - name: Build firmware
        run: |
          source $HOME/esp-idf/export.sh
          idf.py set-target esp32s3
          idf.py build

      # Step 5: Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tomo1firmware-artifacts
          path: build/*