name: ESP32-S3 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Cache ESP-IDF and tools
      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: |
            $HOME/esp-idf
            $HOME/.espressif
          key: esp-idf-${{ runner.os }}-v5.2.1
          restore-keys: |
            esp-idf-${{ runner.os }}-

      - name: Install ESP-IDF
        run: |
          rm -rf $HOME/esp-idf
          git clone --recursive https://github.com/espressif/esp-idf.git $HOME/esp-idf
          cd $HOME/esp-idf
          git fetch --all --tags
          git checkout v5.2.1
          git submodule update --init --recursive
          ./install.sh

      - name: Check ESP-IDF version
        run: |
          cd $HOME/esp-idf
          git describe --tags

      - name: Build firmware with idf.py
        shell: bash
        working-directory: ${{ github.workspace }}
        run: |
          export IDF_PATH=$HOME/esp-idf
          source $IDF_PATH/export.sh
          idf.py set-target esp32s3
          idf.py build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32s3-artifacts
          path: build/*
